spring:
  application:
    name: trading-analyzer
  metrics:
    prometheus:
      enabled: true
  jackson:
    serialization:
      write_dates_as_timestamps: false
      write_durations_as_timestamps: false

logging:
  level:
    org.hibernate.SQL: ERROR
    pl.dombur: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} %-5level [%thread] %X{traceId} %X{userId} %logger{0} - %msg%n"
